export const SURAH_LIST = [
  {number: 1, name: 'الفاتحة', englishName: 'Al-Fatiha', versesCount: 7, type: 'Meccan'},
  {number: 2, name: 'البقرة', englishName: 'Al-Baqarah', versesCount: 286, type: 'Medinan'},
  {number: 3, name: 'آل عمران', englishName: 'Aal-Imran', versesCount: 200, type: 'Medinan'},
  {number: 4, name: 'النساء', englishName: 'An-Nisa', versesCount: 176, type: 'Medinan'},
  {number: 5, name: 'المائدة', englishName: 'Al-Ma\'idah', versesCount: 120, type: 'Medinan'},
  {number: 6, name: 'الأنعام', englishName: 'Al-An\'am', versesCount: 165, type: 'Meccan'},
  {number: 7, name: 'الأعراف', englishName: 'Al-A\'raf', versesCount: 206, type: 'Meccan'},
  {number: 8, name: 'الأنفال', englishName: 'Al-Anfal', versesCount: 75, type: 'Medinan'},
  {number: 9, name: 'التوبة', englishName: 'At-Tawbah', versesCount: 129, type: 'Medinan'},
  {number: 10, name: 'يونس', englishName: 'Yunus', versesCount: 109, type: 'Meccan'},
  {number: 11, name: 'هود', englishName: 'Hud', versesCount: 123, type: 'Meccan'},
  {number: 12, name: 'يوسف', englishName: 'Yusuf', versesCount: 111, type: 'Meccan'},
  {number: 13, name: 'الرعد', englishName: 'Ar-Ra\'d', versesCount: 43, type: 'Medinan'},
  {number: 14, name: 'إبراهيم', englishName: 'Ibrahim', versesCount: 52, type: 'Meccan'},
  {number: 15, name: 'الحجر', englishName: 'Al-Hijr', versesCount: 99, type: 'Meccan'},
  {number: 16, name: 'النحل', englishName: 'An-Nahl', versesCount: 128, type: 'Meccan'},
  {number: 17, name: 'الإسراء', englishName: 'Al-Isra', versesCount: 111, type: 'Meccan'},
  {number: 18, name: 'الكهف', englishName: 'Al-Kahf', versesCount: 110, type: 'Meccan'},
  {number: 19, name: 'مريم', englishName: 'Maryam', versesCount: 98, type: 'Meccan'},
  {number: 20, name: 'طه', englishName: 'Taha', versesCount: 135, type: 'Meccan'},
  {number: 21, name: 'الأنبياء', englishName: 'Al-Anbiya', versesCount: 112, type: 'Meccan'},
  {number: 22, name: 'الحج', englishName: 'Al-Hajj', versesCount: 78, type: 'Medinan'},
  {number: 23, name: 'المؤمنون', englishName: 'Al-Mu\'minun', versesCount: 118, type: 'Meccan'},
  {number: 24, name: 'النور', englishName: 'An-Nur', versesCount: 64, type: 'Medinan'},
  {number: 25, name: 'الفرقان', englishName: 'Al-Furqan', versesCount: 77, type: 'Meccan'},
  {number: 26, name: 'الشعراء', englishName: 'Ash-Shu\'ara', versesCount: 227, type: 'Meccan'},
  {number: 27, name: 'النمل', englishName: 'An-Naml', versesCount: 93, type: 'Meccan'},
  {number: 28, name: 'القصص', englishName: 'Al-Qasas', versesCount: 88, type: 'Meccan'},
  {number: 29, name: 'العنكبوت', englishName: 'Al-Ankabut', versesCount: 69, type: 'Meccan'},
  {number: 30, name: 'الروم', englishName: 'Ar-Rum', versesCount: 60, type: 'Meccan'},
  {number: 31, name: 'لقمان', englishName: 'Luqman', versesCount: 34, type: 'Meccan'},
  {number: 32, name: 'السجدة', englishName: 'As-Sajdah', versesCount: 30, type: 'Meccan'},
  {number: 33, name: 'الأحزاب', englishName: 'Al-Ahzab', versesCount: 73, type: 'Medinan'},
  {number: 34, name: 'سبأ', englishName: 'Saba', versesCount: 54, type: 'Meccan'},
  {number: 35, name: 'فاطر', englishName: 'Fatir', versesCount: 45, type: 'Meccan'},
  {number: 36, name: 'يس', englishName: 'Ya-Sin', versesCount: 83, type: 'Meccan'},
  {number: 37, name: 'الصافات', englishName: 'As-Saffat', versesCount: 182, type: 'Meccan'},
  {number: 38, name: 'ص', englishName: 'Sad', versesCount: 88, type: 'Meccan'},
  {number: 39, name: 'الزمر', englishName: 'Az-Zumar', versesCount: 75, type: 'Meccan'},
  {number: 40, name: 'غافر', englishName: 'Ghafir', versesCount: 85, type: 'Meccan'},
  {number: 41, name: 'فصلت', englishName: 'Fussilat', versesCount: 54, type: 'Meccan'},
  {number: 42, name: 'الشورى', englishName: 'Ash-Shura', versesCount: 53, type: 'Meccan'},
  {number: 43, name: 'الزخرف', englishName: 'Az-Zukhruf', versesCount: 89, type: 'Meccan'},
  {number: 44, name: 'الدخان', englishName: 'Ad-Dukhan', versesCount: 59, type: 'Meccan'},
  {number: 45, name: 'الجاثية', englishName: 'Al-Jathiyah', versesCount: 37, type: 'Meccan'},
  {number: 46, name: 'الأحقاف', englishName: 'Al-Ahqaf', versesCount: 35, type: 'Meccan'},
  {number: 47, name: 'محمد', englishName: 'Muhammad', versesCount: 38, type: 'Medinan'},
  {number: 48, name: 'الفتح', englishName: 'Al-Fath', versesCount: 29, type: 'Medinan'},
  {number: 49, name: 'الحجرات', englishName: 'Al-Hujurat', versesCount: 18, type: 'Medinan'},
  {number: 50, name: 'ق', englishName: 'Qaf', versesCount: 45, type: 'Meccan'},
  {number: 51, name: 'الذاريات', englishName: 'Adh-Dhariyat', versesCount: 60, type: 'Meccan'},
  {number: 52, name: 'الطور', englishName: 'At-Tur', versesCount: 49, type: 'Meccan'},
  {number: 53, name: 'النجم', englishName: 'An-Najm', versesCount: 62, type: 'Meccan'},
  {number: 54, name: 'القمر', englishName: 'Al-Qamar', versesCount: 55, type: 'Meccan'},
  {number: 55, name: 'الرحمن', englishName: 'Ar-Rahman', versesCount: 78, type: 'Medinan'},
  {number: 56, name: 'الواقعة', englishName: 'Al-Waqi\'ah', versesCount: 96, type: 'Meccan'},
  {number: 57, name: 'الحديد', englishName: 'Al-Hadid', versesCount: 29, type: 'Medinan'},
  {number: 58, name: 'المجادلة', englishName: 'Al-Mujadilah', versesCount: 22, type: 'Medinan'},
  {number: 59, name: 'الحشر', englishName: 'Al-Hashr', versesCount: 24, type: 'Medinan'},
  {number: 60, name: 'الممتحنة', englishName: 'Al-Mumtahanah', versesCount: 13, type: 'Medinan'},
  {number: 61, name: 'الصف', englishName: 'As-Saff', versesCount: 14, type: 'Medinan'},
  {number: 62, name: 'الجمعة', englishName: 'Al-Jumu\'ah', versesCount: 11, type: 'Medinan'},
  {number: 63, name: 'المنافقون', englishName: 'Al-Munafiqun', versesCount: 11, type: 'Medinan'},
  {number: 64, name: 'التغابن', englishName: 'At-Taghabun', versesCount: 18, type: 'Medinan'},
  {number: 65, name: 'الطلاق', englishName: 'At-Talaq', versesCount: 12, type: 'Medinan'},
  {number: 66, name: 'التحريم', englishName: 'At-Tahrim', versesCount: 12, type: 'Medinan'},
  {number: 67, name: 'الملك', englishName: 'Al-Mulk', versesCount: 30, type: 'Meccan'},
  {number: 68, name: 'القلم', englishName: 'Al-Qalam', versesCount: 52, type: 'Meccan'},
  {number: 69, name: 'الحاقة', englishName: 'Al-Haqqah', versesCount: 52, type: 'Meccan'},
  {number: 70, name: 'المعارج', englishName: 'Al-Ma\'arij', versesCount: 44, type: 'Meccan'},
  {number: 71, name: 'نوح', englishName: 'Nuh', versesCount: 28, type: 'Meccan'},
  {number: 72, name: 'الجن', englishName: 'Al-Jinn', versesCount: 28, type: 'Meccan'},
  {number: 73, name: 'المزمل', englishName: 'Al-Muzzammil', versesCount: 20, type: 'Meccan'},
  {number: 74, name: 'المدثر', englishName: 'Al-Muddaththir', versesCount: 56, type: 'Meccan'},
  {number: 75, name: 'القيامة', englishName: 'Al-Qiyamah', versesCount: 40, type: 'Meccan'},
  {number: 76, name: 'الإنسان', englishName: 'Al-Insan', versesCount: 31, type: 'Medinan'},
  {number: 77, name: 'المرسلات', englishName: 'Al-Mursalat', versesCount: 50, type: 'Meccan'},
  {number: 78, name: 'النبأ', englishName: 'An-Naba', versesCount: 40, type: 'Meccan'},
  {number: 79, name: 'النازعات', englishName: 'An-Nazi\'at', versesCount: 46, type: 'Meccan'},
  {number: 80, name: 'عبس', englishName: 'Abasa', versesCount: 42, type: 'Meccan'},
  {number: 81, name: 'التكوير', englishName: 'At-Takwir', versesCount: 29, type: 'Meccan'},
  {number: 82, name: 'الانفطار', englishName: 'Al-Infitar', versesCount: 19, type: 'Meccan'},
  {number: 83, name: 'المطففين', englishName: 'Al-Mutaffifin', versesCount: 36, type: 'Meccan'},
  {number: 84, name: 'الانشقاق', englishName: 'Al-Inshiqaq', versesCount: 25, type: 'Meccan'},
  {number: 85, name: 'البروج', englishName: 'Al-Buruj', versesCount: 22, type: 'Meccan'},
  {number: 86, name: 'الطارق', englishName: 'At-Tariq', versesCount: 17, type: 'Meccan'},
  {number: 87, name: 'الأعلى', englishName: 'Al-A\'la', versesCount: 19, type: 'Meccan'},
  {number: 88, name: 'الغاشية', englishName: 'Al-Ghashiyah', versesCount: 26, type: 'Meccan'},
  {number: 89, name: 'الفجر', englishName: 'Al-Fajr', versesCount: 30, type: 'Meccan'},
  {number: 90, name: 'البلد', englishName: 'Al-Balad', versesCount: 20, type: 'Meccan'},
  {number: 91, name: 'الشمس', englishName: 'Ash-Shams', versesCount: 15, type: 'Meccan'},
  {number: 92, name: 'الليل', englishName: 'Al-Layl', versesCount: 21, type: 'Meccan'},
  {number: 93, name: 'الضحى', englishName: 'Ad-Duha', versesCount: 11, type: 'Meccan'},
  {number: 94, name: 'الشرح', englishName: 'Ash-Sharh', versesCount: 8, type: 'Meccan'},
  {number: 95, name: 'التين', englishName: 'At-Tin', versesCount: 8, type: 'Meccan'},
  {number: 96, name: 'العلق', englishName: 'Al-Alaq', versesCount: 19, type: 'Meccan'},
  {number: 97, name: 'القدر', englishName: 'Al-Qadr', versesCount: 5, type: 'Meccan'},
  {number: 98, name: 'البينة', englishName: 'Al-Bayyinah', versesCount: 8, type: 'Medinan'},
  {number: 99, name: 'الزلزلة', englishName: 'Az-Zalzalah', versesCount: 8, type: 'Medinan'},
  {number: 100, name: 'العاديات', englishName: 'Al-Adiyat', versesCount: 11, type: 'Meccan'},
  {number: 101, name: 'القارعة', englishName: 'Al-Qari\'ah', versesCount: 11, type: 'Meccan'},
  {number: 102, name: 'التكاثر', englishName: 'At-Takathur', versesCount: 8, type: 'Meccan'},
  {number: 103, name: 'العصر', englishName: 'Al-Asr', versesCount: 3, type: 'Meccan'},
  {number: 104, name: 'الهمزة', englishName: 'Al-Humazah', versesCount: 9, type: 'Meccan'},
  {number: 105, name: 'الفيل', englishName: 'Al-Fil', versesCount: 5, type: 'Meccan'},
  {number: 106, name: 'قريش', englishName: 'Quraysh', versesCount: 4, type: 'Meccan'},
  {number: 107, name: 'الماعون', englishName: 'Al-Ma\'un', versesCount: 7, type: 'Meccan'},
  {number: 108, name: 'الكوثر', englishName: 'Al-Kawthar', versesCount: 3, type: 'Meccan'},
  {number: 109, name: 'الكافرون', englishName: 'Al-Kafirun', versesCount: 6, type: 'Meccan'},
  {number: 110, name: 'النصر', englishName: 'An-Nasr', versesCount: 3, type: 'Medinan'},
  {number: 111, name: 'المسد', englishName: 'Al-Masad', versesCount: 5, type: 'Meccan'},
  {number: 112, name: 'الإخلاص', englishName: 'Al-Ikhlas', versesCount: 4, type: 'Meccan'},
  {number: 113, name: 'الفلق', englishName: 'Al-Falaq', versesCount: 5, type: 'Meccan'},
  {number: 114, name: 'الناس', englishName: 'An-Nas', versesCount: 6, type: 'Meccan'},
];

export const RECITERS = [
  {id: 'ar.alafasy', name: 'مشاري العفاسي', server: 'server8', folder: 'afs'},
  {id: 'ar.minshawi', name: 'محمد صديق المنشاوي', server: 'server10', folder: 'Minshawy'},
  {id: 'ar.husary', name: 'محمود خليل الحصري', server: 'server13', folder: 'Husary'},
  {id: 'ar.abdulbasit', name: 'عبد الباسط عبد الصمد', server: 'server7', folder: 'AbdulBasit'},
  {id: 'ar.mahermuaiqly', name: 'ماهر المعيقلي', server: 'server12', folder: 'maher'},
  {id: 'ar.sudais', name: 'عبد الرحمن السديس', server: 'server11', folder: 'sudais'},
  {id: 'ar.shuraym', name: 'سعود الشريم', server: 'server6', folder: 'shuraym'},
  {id: 'ar.ghamdi', name: 'سعد الغامدي', server: 'server2', folder: 'ghamdi'},
];

export const PRAYER_NAMES = ['Fajr', 'Sunrise', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'];
export const PRAYER_ARABIC = {
  Fajr: 'الفجر',
  Sunrise: 'الشروق',
  Dhuhr: 'الظهر',
  Asr: 'العصر',
  Maghrib: 'المغرب',
  Isha: 'العشاء',
};
export const PRAYER_ICONS = {
  Fajr: '🌅',
  Sunrise: '☀️',
  Dhuhr: '🌤️',
  Asr: '🌤️',
  Maghrib: '🌆',
  Isha: '🌙',
};
export const PRAYER_COLORS = {
  Fajr: '#1A237E',
  Sunrise: '#F59E0B',
  Dhuhr: '#F59E0B',
  Asr: '#D97706',
  Maghrib: '#DC2626',
  Isha: '#312E81',
};

export const CALCULATION_METHODS = [
  {id: 1, name: 'رابطة العالم الإسلامي'},
  {id: 2, name: 'الجمعية الإسلامية لأمريكا الشمالية'},
  {id: 3, name: 'الهيئة المصرية العامة للمساحة'},
  {id: 4, name: 'أم القرى - مكة المكرمة'},
  {id: 5, name: 'جامعة العلوم الإسلامية - كراتشي'},
  {id: 8, name: 'دولة الإمارات العربية المتحدة'},
  {id: 12, name: 'اتحاد فرنسا'},
  {id: 13, name: 'دولة الكويت'},
];

export const MADHHABS = [
  {id: 0, name: 'الشافعي'},
  {id: 1, name: 'الحنفي'},
];
